/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/cache/clear": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Cache Clear
         * @description Admin-only reset for the Entity/Hazard LRU and DuckDB computation cache.
         *
         *     Not surfaced in the UI: intended for support flows that need a
         *     guaranteed cold repeat of a scenario (e.g. when validating a fix to
         *     a CLIMADA bug that an old cached result is masking).
         */
        post: operations["cache_clear_api_v1_cache_clear_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/countries": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Countries
         * @description Return the countries RISK WISE can run — built-in plus custom drop-ins.
         *
         *     Each entry carries a ``source`` field (``"builtin"`` or ``"custom"``)
         *     so the frontend can label them distinctly (issue #56, Scenario 2).
         *     Invalid custom drop-ins are skipped at startup (see
         *     :func:`_scan_user_data_countries`) and do not appear here.
         */
        get: operations["countries_api_v1_countries_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/custom-data": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Custom Data List */
        get: operations["custom_data_list_api_v1_custom_data_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/custom-data/import": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Custom Data Import */
        post: operations["custom_data_import_api_v1_custom_data_import_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/custom-data/validate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Custom Data Validate */
        post: operations["custom_data_validate_api_v1_custom_data_validate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/custom-data/{iso3}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Custom Data Delete */
        delete: operations["custom_data_delete_api_v1_custom_data__iso3__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/data/validate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Data Validate */
        post: operations["data_validate_api_v1_data_validate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_v1_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/macro/chart-data": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Macro Chart Data */
        post: operations["macro_chart_data_api_v1_macro_chart_data_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/macro/cred-output": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Macro Cred Output */
        get: operations["macro_cred_output_api_v1_macro_cred_output_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/macro/datasets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Macro Datasets */
        get: operations["macro_datasets_api_v1_macro_datasets_get"];
        put?: never;
        /** Macro Datasets Upload */
        post: operations["macro_datasets_upload_api_v1_macro_datasets_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/macro/datasets/{dataset_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Macro Datasets Delete */
        delete: operations["macro_datasets_delete_api_v1_macro_datasets__dataset_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/measures/datasets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Measure Datasets */
        get: operations["measure_datasets_api_v1_measures_datasets_get"];
        put?: never;
        /** Measure Datasets Upload */
        post: operations["measure_datasets_upload_api_v1_measures_datasets_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/measures/datasets/{measure_set_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Measure Datasets Delete */
        delete: operations["measure_datasets_delete_api_v1_measures_datasets__measure_set_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/measures/{country}/{hazard}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Measures */
        get: operations["measures_api_v1_measures__country___hazard__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/scenario/cost-benefit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Scenario Cost Benefit */
        get: operations["scenario_cost_benefit_api_v1_scenario_cost_benefit_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/scenario/import": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Scenario Import */
        post: operations["scenario_import_api_v1_scenario_import_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/scenario/run": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Scenario Run */
        post: operations["scenario_run_api_v1_scenario_run_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/scenario/waterfall": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Scenario Waterfall */
        get: operations["scenario_waterfall_api_v1_scenario_waterfall_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/scenario/{job_id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Scenario Cancel */
        post: operations["scenario_cancel_api_v1_scenario__job_id__cancel_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/scenario/{job_id}/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Scenario Stream */
        get: operations["scenario_stream_api_v1_scenario__job_id__stream_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/scenario/{scenario_id}/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Scenario Export Stream
         * @description Stream the ``.riskwise-scenario`` ZIP for direct download.
         *
         *     Cleanup runs via Starlette's ``BackgroundTask`` after the response
         *     completes successfully. A client that drops mid-download leaves the
         *     temp dir behind — acceptable for a manually-triggered single-scenario
         *     export at this scale; a periodic sweep can reap stragglers if needed.
         */
        get: operations["scenario_export_stream_api_v1_scenario__scenario_id__export_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/scenario/{scenario_id}/export-data": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Scenario Export Data
         * @description Build a ``.riskwise-scenario`` at a temp path and return its location.
         */
        get: operations["scenario_export_data_api_v1_scenario__scenario_id__export_data_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/scenarios": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Scenarios Endpoint */
        get: operations["list_scenarios_endpoint_api_v1_scenarios_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/scenarios/{scenario_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Scenario Endpoint */
        get: operations["get_scenario_endpoint_api_v1_scenarios__scenario_id__get"];
        put?: never;
        post?: never;
        /** Delete Scenario Endpoint */
        delete: operations["delete_scenario_endpoint_api_v1_scenarios__scenario_id__delete"];
        options?: never;
        head?: never;
        /** Patch Scenario Endpoint */
        patch: operations["patch_scenario_endpoint_api_v1_scenarios__scenario_id__patch"];
        trace?: never;
    };
    "/api/v1/scenarios/{scenario_id}/hydrate-temp": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Hydrate Scenario Temp Endpoint
         * @description Rewrite the saved scenario's blobs back into the temp dir.
         *
         *     Required by the Workspace ``Restore`` flow: the maps and the
         *     waterfall/cost-benefit charts read from per-run JSON files, so the
         *     renderer cannot show the restored state until those files exist on
         *     disk again. See ``backend.run_hydrate_scenario_temp`` for details.
         */
        post: operations["hydrate_scenario_temp_endpoint_api_v1_scenarios__scenario_id__hydrate_temp_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/scenarios/{scenario_id}/save": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Save Scenario Endpoint */
        post: operations["save_scenario_endpoint_api_v1_scenarios__scenario_id__save_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/scenarios/{scenario_id}/snapshots": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Snapshots Endpoint */
        get: operations["list_snapshots_endpoint_api_v1_scenarios__scenario_id__snapshots_get"];
        put?: never;
        /** Create Snapshot Endpoint */
        post: operations["create_snapshot_endpoint_api_v1_scenarios__scenario_id__snapshots_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Settings Endpoint */
        get: operations["get_settings_endpoint_api_v1_settings_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Patch Settings Endpoint */
        patch: operations["patch_settings_endpoint_api_v1_settings_patch"];
        trace?: never;
    };
    "/api/v1/snapshots/{snapshot_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Snapshot Endpoint */
        delete: operations["delete_snapshot_endpoint_api_v1_snapshots__snapshot_id__delete"];
        options?: never;
        head?: never;
        /** Update Snapshot Endpoint */
        patch: operations["update_snapshot_endpoint_api_v1_snapshots__snapshot_id__patch"];
        trace?: never;
    };
    "/api/v1/snapshots/{snapshot_id}/image": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Snapshot Image Endpoint */
        get: operations["get_snapshot_image_endpoint_api_v1_snapshots__snapshot_id__image_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/temp/clear": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Temp Clear */
        post: operations["temp_clear_api_v1_temp_clear_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workspace/export-data": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Workspace Export
         * @description Build a ``.riskwise-workspace`` ZIP at a temp path and return its location.
         *
         *     The Electron main process copies the file to the user's chosen save
         *     location and removes the temp copy afterwards, so the backend never
         *     needs to stream binary through the IPC channel.
         */
        get: operations["workspace_export_api_v1_workspace_export_data_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workspace/import": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Workspace Import */
        post: operations["workspace_import_api_v1_workspace_import_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ChartDataDataset */
        ChartDataDataset: {
            /** Data */
            data?: (number | null)[];
            /** Label */
            label?: string | null;
        } & {
            [key: string]: unknown;
        };
        /** ChartDataPayload */
        ChartDataPayload: {
            /** Datasets */
            datasets?: components["schemas"]["ChartDataDataset"][];
            /**
             * Title
             * @default
             */
            title: string;
            /** Years */
            years?: (number | string)[];
        } & {
            [key: string]: unknown;
        };
        /** CostBenefitMeasure */
        CostBenefitMeasure: {
            /** Benefit */
            benefit: number;
            /** Benefit Cost Ratio */
            benefit_cost_ratio: number;
            /** Cost */
            cost: number;
            /** Display Name */
            display_name?: string | null;
            /** Name */
            name: string;
        };
        /** CostBenefitPayload */
        CostBenefitPayload: {
            /**
             * Currency Unit
             * @default
             */
            currency_unit: string;
            /** Future Year */
            future_year: number;
            /** Measures */
            measures?: components["schemas"]["CostBenefitMeasure"][];
            /** Present Year */
            present_year: number;
        };
        /** CostBenefitResponse */
        CostBenefitResponse: {
            data: components["schemas"]["CostBenefitPayload"];
            status: components["schemas"]["Status"];
        };
        /** CountriesResponse */
        CountriesResponse: {
            /** Data */
            data: components["schemas"]["Country"][];
            status: components["schemas"]["Status"];
        };
        /** Country */
        Country: {
            /** Code */
            code: string;
            /** Name */
            name: string;
            /**
             * Source
             * @default builtin
             * @enum {string}
             */
            source: "builtin" | "custom";
        };
        /**
         * CreateSnapshotRequest
         * @description Body for ``POST /api/v1/scenarios/{id}/snapshots``.
         */
        CreateSnapshotRequest: {
            /** Caption */
            caption?: string | null;
            /** Image Base64 */
            image_base64: string;
            /** Snapshot Type */
            snapshot_type: string;
            /** Surface */
            surface?: ("hazard" | "exposure" | "impact" | "adaptation") | null;
            /** Title */
            title?: string | null;
        };
        /** CreateSnapshotResponse */
        CreateSnapshotResponse: {
            data: components["schemas"]["SnapshotItem"];
            status: components["schemas"]["Status"];
        };
        /** CredDataset */
        CredDataset: {
            /** Id */
            id: string;
            /** Is Builtin */
            is_builtin: boolean;
            /** Name */
            name: string;
            /** Sha256 */
            sha256?: string | null;
            /** Source */
            source?: string | null;
            /**
             * Uploaded At
             * Format: date-time
             */
            uploaded_at: string;
        };
        /** CredDatasetDeleteData */
        CredDatasetDeleteData: {
            /** Id */
            id: string;
        };
        /** CredDatasetDeleteResponse */
        CredDatasetDeleteResponse: {
            data: components["schemas"]["CredDatasetDeleteData"];
            status: components["schemas"]["Status"];
        };
        /**
         * CredDatasetUploadRequest
         * @description Payload for POST ``/api/v1/macro/datasets``.
         *
         *     The renderer passes the xlsx path on disk (same pattern as custom-data
         *     imports) rather than multipart bytes — Electron and the backend share
         *     the user's filesystem, so streaming through the loopback channel is
         *     unnecessary overhead.
         */
        CredDatasetUploadRequest: {
            /** Name */
            name: string;
            /** Xlsx Path */
            xlsx_path: string;
        };
        /** CredDatasetUploadResponse */
        CredDatasetUploadResponse: {
            data: components["schemas"]["CredDataset"];
            status: components["schemas"]["Status"];
        };
        /** CredDatasetsResponse */
        CredDatasetsResponse: {
            /** Data */
            data: components["schemas"]["CredDataset"][];
            status: components["schemas"]["Status"];
        };
        /** CustomCountryEntry */
        CustomCountryEntry: {
            /** Country Name */
            country_name: string;
            /** Installed At */
            installed_at: string;
            /** Iso3 */
            iso3: string;
            /** Source */
            source: string;
        };
        /** CustomDataDeleteData */
        CustomDataDeleteData: {
            /** Iso3 */
            iso3: string;
        };
        /** CustomDataDeleteResponse */
        CustomDataDeleteResponse: {
            data: components["schemas"]["CustomDataDeleteData"];
            status: components["schemas"]["Status"];
        };
        /** CustomDataImportData */
        CustomDataImportData: {
            /** Country Name */
            country_name: string;
            /** Installed At */
            installed_at: string;
            /** Iso3 */
            iso3: string;
        };
        /** CustomDataImportRequest */
        CustomDataImportRequest: {
            /** Zip Path */
            zip_path: string;
        };
        /** CustomDataImportResponse */
        CustomDataImportResponse: {
            data: components["schemas"]["CustomDataImportData"];
            status: components["schemas"]["Status"];
        };
        /** CustomDataListData */
        CustomDataListData: {
            /** Countries */
            countries: components["schemas"]["CustomCountryEntry"][];
        };
        /** CustomDataListResponse */
        CustomDataListResponse: {
            data: components["schemas"]["CustomDataListData"];
            status: components["schemas"]["Status"];
        };
        /** CustomDataValidateData */
        CustomDataValidateData: {
            /** Country Name */
            country_name: string;
            /** Errors */
            errors: string[];
            /** Iso3 */
            iso3: string;
            /** Valid */
            valid: boolean;
        };
        /** CustomDataValidateRequest */
        CustomDataValidateRequest: {
            /** Zip Path */
            zip_path: string;
        };
        /** CustomDataValidateResponse */
        CustomDataValidateResponse: {
            data: components["schemas"]["CustomDataValidateData"];
            status: components["schemas"]["Status"];
        };
        /** DataValidateData */
        DataValidateData: {
            /** Data */
            data: {
                [key: string]: unknown;
            };
        };
        /** DataValidateRequest */
        DataValidateRequest: {
            /** Country */
            country: string;
            /** Datatype */
            dataType: string;
        };
        /** DataValidateResponse */
        DataValidateResponse: {
            data: components["schemas"]["DataValidateData"];
            status: components["schemas"]["Status"];
        };
        /** DeleteScenarioResponse */
        DeleteScenarioResponse: {
            /** Data */
            data: {
                [key: string]: unknown;
            };
            status: components["schemas"]["Status"];
        };
        /** DeleteSnapshotResponse */
        DeleteSnapshotResponse: {
            /** Data */
            data: {
                [key: string]: unknown;
            };
            status: components["schemas"]["Status"];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            /**
             * Status
             * @constant
             */
            status: "ok";
        };
        /**
         * HydrateScenarioData
         * @description Payload returned by ``POST /api/v1/scenarios/{id}/hydrate-temp``.
         *
         *     ``written`` lists the result types that were rewritten to the temp
         *     directory; absent types (e.g. ``costben_data`` on a historical scenario)
         *     are silently skipped at the writer.
         */
        HydrateScenarioData: {
            /** Written */
            written: string[];
        };
        /** HydrateScenarioResponse */
        HydrateScenarioResponse: {
            data: components["schemas"]["HydrateScenarioData"];
            status: components["schemas"]["Status"];
        };
        /** JobAcceptedResponse */
        JobAcceptedResponse: {
            /**
             * Job Id
             * @description UUID for the long-running scenario job
             */
            job_id: string;
        };
        /** MacroChartDataRequest */
        MacroChartDataRequest: {
            /** Countryname */
            countryName?: string | null;
            /** Dataset Id */
            dataset_id?: string | null;
            /** Scenario */
            scenario?: string | null;
            /** Sector */
            sector?: string | null;
            /** Variable */
            variable?: string | null;
        } & {
            [key: string]: unknown;
        };
        /** MacroChartDataResponse */
        MacroChartDataResponse: {
            data: components["schemas"]["ChartDataPayload"];
            status: components["schemas"]["Status"];
        };
        /**
         * MacroCredOutputResponse
         * @description The CRED output is a flat list of dict rows whose keys vary by export.
         *
         *     Frontend code groups and filters them client-side, so we don't pin a row
         *     schema here.
         */
        MacroCredOutputResponse: {
            /** Data */
            data: {
                [key: string]: unknown;
            }[];
            status: components["schemas"]["Status"];
        };
        /** Measure */
        Measure: {
            /** Cost Factor */
            cost_factor: number;
            /** Country */
            country?: string | null;
            /** Description */
            description?: string | null;
            /** Exposure Type */
            exposure_type?: string | null;
            /** Hazard Reduction Percentage */
            hazard_reduction_percentage: number;
            /** Hazard Type */
            hazard_type: string;
            /** Id */
            id: string;
            /** Is Builtin */
            is_builtin: boolean;
            /** Measure Set Id */
            measure_set_id: string;
            /** Measure Set Name */
            measure_set_name: string;
            /** Name */
            name: string;
            /** Source Reference */
            source_reference?: string | null;
        };
        /** MeasureSet */
        MeasureSet: {
            /** Countries */
            countries?: string | null;
            /** Hazards */
            hazards?: string | null;
            /** Id */
            id: string;
            /** Is Builtin */
            is_builtin: boolean;
            /**
             * Measure Count
             * @default 0
             */
            measure_count: number;
            /** Name */
            name: string;
            /** Sha256 */
            sha256?: string | null;
            /**
             * Uploaded At
             * Format: date-time
             */
            uploaded_at: string;
        };
        /** MeasureSetDeleteData */
        MeasureSetDeleteData: {
            /** Id */
            id: string;
        };
        /** MeasureSetDeleteResponse */
        MeasureSetDeleteResponse: {
            data: components["schemas"]["MeasureSetDeleteData"];
            status: components["schemas"]["Status"];
        };
        /**
         * MeasureSetUploadRequest
         * @description Payload for POST ``/api/v1/measures/datasets``.
         *
         *     As with the CRED upload endpoint, the renderer passes the xlsx path on
         *     disk rather than multipart bytes — Electron and the backend share the
         *     user's filesystem, so streaming through the loopback channel is
         *     unnecessary overhead.
         */
        MeasureSetUploadRequest: {
            /** Name */
            name: string;
            /** Xlsx Path */
            xlsx_path: string;
        };
        /** MeasureSetUploadResponse */
        MeasureSetUploadResponse: {
            data: components["schemas"]["MeasureSet"];
            status: components["schemas"]["Status"];
        };
        /** MeasureSetsResponse */
        MeasureSetsResponse: {
            /** Data */
            data: components["schemas"]["MeasureSet"][];
            status: components["schemas"]["Status"];
        };
        /** MeasuresData */
        MeasuresData: {
            /** Adaptationmeasures */
            adaptationMeasures: string[];
            /** Measures */
            measures?: components["schemas"]["Measure"][];
        };
        /** MeasuresResponse */
        MeasuresResponse: {
            data: components["schemas"]["MeasuresData"];
            status: components["schemas"]["Status"];
        };
        /**
         * PatchScenarioRequest
         * @description Body for ``PATCH /api/v1/scenarios/{id}`` — partial metadata update.
         */
        PatchScenarioRequest: {
            /** Name */
            name?: string | null;
            /** Notes */
            notes?: string | null;
            /** Tags */
            tags?: string | null;
        };
        /**
         * SaveScenarioRequest
         * @description Body for ``POST /api/v1/scenarios/{id}/save`` — the save-as dialog.
         */
        SaveScenarioRequest: {
            /** Name */
            name: string;
            /** Notes */
            notes?: string | null;
            /** Tags */
            tags?: string | null;
        };
        /** SaveScenarioResponse */
        SaveScenarioResponse: {
            data: components["schemas"]["ScenarioWorkspaceItem"];
            status: components["schemas"]["Status"];
        };
        /**
         * ScenarioDetailPayload
         * @description Full scenario: metadata row plus the result blobs keyed by type.
         *
         *     Result values are pre-decoded JSON strings — the frontend parses them
         *     as needed. Storing raw strings keeps the payload auditable at the
         *     network boundary without adding a per-type Pydantic schema here.
         */
        ScenarioDetailPayload: {
            /** Results */
            results?: {
                [key: string]: string;
            };
            scenario: components["schemas"]["ScenarioWorkspaceItem"];
        };
        /** ScenarioDetailResponse */
        ScenarioDetailResponse: {
            data: components["schemas"]["ScenarioDetailPayload"];
            status: components["schemas"]["Status"];
        };
        /**
         * ScenarioExportData
         * @description Shape returned by ``GET /api/v1/scenario/{id}/export-data`` (#122).
         *
         *     The endpoint that streams the binary uses ``FileResponse`` directly and
         *     does not return JSON; this model exists so the matching "build the ZIP
         *     at a temp path" helper used by Electron has a typed envelope to mirror
         *     the workspace export flow.
         */
        ScenarioExportData: {
            /** Export Path */
            export_path: string;
            /** Filename */
            filename: string;
            /** Scenario Id */
            scenario_id: string;
        };
        /** ScenarioExportResponse */
        ScenarioExportResponse: {
            data: components["schemas"]["ScenarioExportData"];
            status: components["schemas"]["Status"];
        };
        /** ScenarioImportData */
        ScenarioImportData: {
            /** Name */
            name?: string | null;
            /** Scenario Id */
            scenario_id: string;
        };
        /**
         * ScenarioImportRequest
         * @description Body posted to ``POST /api/v1/scenario/import`` (#122).
         *
         *     The renderer never reads the ZIP bytes; Electron's open dialog hands
         *     the absolute path to the backend, which validates ``provenance.json``
         *     and inserts the scenario as read-only (``is_imported = TRUE``).
         */
        ScenarioImportRequest: {
            /** Import Path */
            import_path: string;
        };
        /** ScenarioImportResponse */
        ScenarioImportResponse: {
            data: components["schemas"]["ScenarioImportData"];
            status: components["schemas"]["Status"];
        };
        /** ScenarioListResponse */
        ScenarioListResponse: {
            /** Data */
            data: components["schemas"]["ScenarioWorkspaceItem"][];
            status: components["schemas"]["Status"];
        };
        /**
         * ScenarioRunRequest
         * @description Inputs the renderer collects before kicking off a scenario run.
         *
         *     The CLIMADA layer reads these as plain strings/ints; we keep the model
         *     permissive so users can submit only the subset of fields a given hazard or
         *     exposure flow actually needs.
         */
        ScenarioRunRequest: {
            /** Annualgrowth */
            annualGrowth?: number | null;
            /** Assettype */
            assetType?: ("economic" | "non_economic") | null;
            /** Countryname */
            countryName?: string | null;
            /** Exposurefile */
            exposureFile?: string | null;
            /** Exposuretype */
            exposureType?: string | null;
            /** Hazardfile */
            hazardFile?: string | null;
            /** Hazardtype */
            hazardType?: string | null;
            /** Isera */
            isEra?: boolean | null;
            /** Scenario */
            scenario?: string | null;
            /** Selectedmeasureids */
            selectedMeasureIds?: string[];
            /** Timehorizon */
            timeHorizon?: number[] | null;
        } & {
            [key: string]: unknown;
        };
        /**
         * ScenarioWorkspaceItem
         * @description A saved-scenario row as it appears in the workspace list.
         */
        ScenarioWorkspaceItem: {
            /** Annual Growth */
            annual_growth?: number | null;
            /** App Option */
            app_option?: string | null;
            /** App Version */
            app_version?: string | null;
            /** Asset Type */
            asset_type?: string | null;
            /** Climada Version */
            climada_version?: string | null;
            /** Computed At */
            computed_at?: string | null;
            /** Country */
            country?: string | null;
            /** Country Config Sha256 */
            country_config_sha256?: string | null;
            /** Created At */
            created_at?: string | null;
            /** Engine */
            engine?: string | null;
            /** Engine Version */
            engine_version?: string | null;
            /** Entity Data Sha256 */
            entity_data_sha256?: string | null;
            /** Exposure Type */
            exposure_type?: string | null;
            /** Future Year */
            future_year?: number | null;
            /** Hazard Data Sha256 */
            hazard_data_sha256?: string | null;
            /** Hazard Type */
            hazard_type?: string | null;
            /** Id */
            id: string;
            /** Is Era */
            is_era?: boolean | null;
            /**
             * Is Imported
             * @default false
             */
            is_imported: boolean;
            /** Name */
            name?: string | null;
            /** Notes */
            notes?: string | null;
            /** Random Seed */
            random_seed?: number | null;
            /** Ref Year */
            ref_year?: number | null;
            /**
             * Saved
             * @default false
             */
            saved: boolean;
            /** Scenario */
            scenario?: string | null;
            /** Status */
            status?: string | null;
            /** Tags */
            tags?: string | null;
        };
        /** SnapshotItem */
        SnapshotItem: {
            /** Caption */
            caption?: string | null;
            /** Created At */
            created_at?: string | null;
            /** Id */
            id: string;
            /** Scenario Id */
            scenario_id: string;
            /** Snapshot Type */
            snapshot_type: string;
            /** Surface */
            surface?: ("hazard" | "exposure" | "impact" | "adaptation") | null;
            /** Title */
            title?: string | null;
        };
        /** SnapshotListResponse */
        SnapshotListResponse: {
            /** Data */
            data: components["schemas"]["SnapshotItem"][];
            status: components["schemas"]["Status"];
        };
        /** Status */
        Status: {
            /** Code */
            code: number;
            /**
             * Message
             * @default
             */
            message: string;
        };
        /** TempClearResponse */
        TempClearResponse: {
            /** Error */
            error?: string | null;
            /** Message */
            message?: string | null;
            /** Success */
            success: boolean;
        };
        /** UpdateSnapshotRequest */
        UpdateSnapshotRequest: {
            /** Caption */
            caption?: string | null;
            /** Surface */
            surface?: ("hazard" | "exposure" | "impact" | "adaptation") | null;
            /** Title */
            title?: string | null;
        };
        /** UpdateSnapshotResponse */
        UpdateSnapshotResponse: {
            data: components["schemas"]["SnapshotItem"];
            status: components["schemas"]["Status"];
        };
        /** UpdateUserSettingsRequest */
        UpdateUserSettingsRequest: {
            /** Report Currency */
            report_currency?: ("EUR" | "USD" | "GBP" | "CHF" | "THB" | "EGP") | null;
            /** Report Locale */
            report_locale?: ("en-US" | "en-GB" | "de-DE" | "fr-FR" | "es-ES" | "th-TH" | "ar-EG") | null;
        };
        /** UserSettings */
        UserSettings: {
            /**
             * Report Currency
             * @default EUR
             * @enum {string}
             */
            report_currency: "EUR" | "USD" | "GBP" | "CHF" | "THB" | "EGP";
            /**
             * Report Locale
             * @default en-US
             * @enum {string}
             */
            report_locale: "en-US" | "en-GB" | "de-DE" | "fr-FR" | "es-ES" | "th-TH" | "ar-EG";
        };
        /** UserSettingsResponse */
        UserSettingsResponse: {
            data: components["schemas"]["UserSettings"];
            status: components["schemas"]["Status"];
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /** WaterfallCategory */
        WaterfallCategory: {
            /** Base */
            base: number;
            /** Key */
            key: string;
            /** Label */
            label: string;
            /** Value */
            value: number;
        };
        /** WaterfallPayload */
        WaterfallPayload: {
            /** Categories */
            categories: components["schemas"]["WaterfallCategory"][];
            /** Future Year */
            future_year: number;
            /**
             * Measurement Unit
             * @default
             */
            measurement_unit: string;
            /** Present Year */
            present_year: number;
        };
        /** WaterfallResponse */
        WaterfallResponse: {
            data?: components["schemas"]["WaterfallPayload"] | null;
            status: components["schemas"]["Status"];
        };
        /**
         * WorkspaceExportData
         * @description Shape returned by ``GET /api/v1/workspace/export-data``.
         *
         *     ``export_path`` points to a file on local disk under the system temp
         *     directory. The Electron main process copies it to the user's chosen
         *     destination and unlinks the source afterwards.
         */
        WorkspaceExportData: {
            /** App Version */
            app_version: string;
            /** Export Date */
            export_date: string;
            /** Export Path */
            export_path: string;
            /** Scenario Count */
            scenario_count: number;
        };
        /** WorkspaceExportResponse */
        WorkspaceExportResponse: {
            data: components["schemas"]["WorkspaceExportData"];
            status: components["schemas"]["Status"];
        };
        /** WorkspaceImportData */
        WorkspaceImportData: {
            /** Imported Count */
            imported_count: number;
            /** Skipped Count */
            skipped_count: number;
        };
        /**
         * WorkspaceImportRequest
         * @description Body posted to ``POST /api/v1/workspace/import``.
         *
         *     The renderer never reads the ZIP bytes — Electron's open dialog hands
         *     back an absolute path, and the backend consumes the file from disk.
         */
        WorkspaceImportRequest: {
            /** Import Path */
            import_path: string;
        };
        /** WorkspaceImportResponse */
        WorkspaceImportResponse: {
            data: components["schemas"]["WorkspaceImportData"];
            status: components["schemas"]["Status"];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    cache_clear_api_v1_cache_clear_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    countries_api_v1_countries_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CountriesResponse"];
                };
            };
        };
    };
    custom_data_list_api_v1_custom_data_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CustomDataListResponse"];
                };
            };
        };
    };
    custom_data_import_api_v1_custom_data_import_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CustomDataImportRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CustomDataImportResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    custom_data_validate_api_v1_custom_data_validate_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CustomDataValidateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CustomDataValidateResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    custom_data_delete_api_v1_custom_data__iso3__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                iso3: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CustomDataDeleteResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    data_validate_api_v1_data_validate_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DataValidateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DataValidateResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_api_v1_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    macro_chart_data_api_v1_macro_chart_data_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MacroChartDataRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MacroChartDataResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    macro_cred_output_api_v1_macro_cred_output_get: {
        parameters: {
            query?: {
                dataset_id?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MacroCredOutputResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    macro_datasets_api_v1_macro_datasets_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CredDatasetsResponse"];
                };
            };
        };
    };
    macro_datasets_upload_api_v1_macro_datasets_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CredDatasetUploadRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CredDatasetUploadResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    macro_datasets_delete_api_v1_macro_datasets__dataset_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                dataset_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CredDatasetDeleteResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    measure_datasets_api_v1_measures_datasets_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeasureSetsResponse"];
                };
            };
        };
    };
    measure_datasets_upload_api_v1_measures_datasets_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MeasureSetUploadRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeasureSetUploadResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    measure_datasets_delete_api_v1_measures_datasets__measure_set_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                measure_set_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeasureSetDeleteResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    measures_api_v1_measures__country___hazard__get: {
        parameters: {
            query?: {
                measure_set_id?: string | null;
            };
            header?: never;
            path: {
                country: string;
                hazard: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeasuresResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    scenario_cost_benefit_api_v1_scenario_cost_benefit_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CostBenefitResponse"];
                };
            };
        };
    };
    scenario_import_api_v1_scenario_import_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ScenarioImportRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScenarioImportResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    scenario_run_api_v1_scenario_run_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ScenarioRunRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobAcceptedResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    scenario_waterfall_api_v1_scenario_waterfall_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WaterfallResponse"];
                };
            };
        };
    };
    scenario_cancel_api_v1_scenario__job_id__cancel_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    scenario_stream_api_v1_scenario__job_id__stream_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    scenario_export_stream_api_v1_scenario__scenario_id__export_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                scenario_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    scenario_export_data_api_v1_scenario__scenario_id__export_data_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                scenario_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScenarioExportResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_scenarios_endpoint_api_v1_scenarios_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScenarioListResponse"];
                };
            };
        };
    };
    get_scenario_endpoint_api_v1_scenarios__scenario_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                scenario_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScenarioDetailResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_scenario_endpoint_api_v1_scenarios__scenario_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                scenario_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeleteScenarioResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    patch_scenario_endpoint_api_v1_scenarios__scenario_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                scenario_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PatchScenarioRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SaveScenarioResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    hydrate_scenario_temp_endpoint_api_v1_scenarios__scenario_id__hydrate_temp_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                scenario_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HydrateScenarioResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    save_scenario_endpoint_api_v1_scenarios__scenario_id__save_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                scenario_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SaveScenarioRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SaveScenarioResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_snapshots_endpoint_api_v1_scenarios__scenario_id__snapshots_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                scenario_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SnapshotListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_snapshot_endpoint_api_v1_scenarios__scenario_id__snapshots_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                scenario_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateSnapshotRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreateSnapshotResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_settings_endpoint_api_v1_settings_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserSettingsResponse"];
                };
            };
        };
    };
    patch_settings_endpoint_api_v1_settings_patch: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateUserSettingsRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserSettingsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_snapshot_endpoint_api_v1_snapshots__snapshot_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                snapshot_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeleteSnapshotResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_snapshot_endpoint_api_v1_snapshots__snapshot_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                snapshot_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateSnapshotRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UpdateSnapshotResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_snapshot_image_endpoint_api_v1_snapshots__snapshot_id__image_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                snapshot_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    temp_clear_api_v1_temp_clear_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TempClearResponse"];
                };
            };
        };
    };
    workspace_export_api_v1_workspace_export_data_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkspaceExportResponse"];
                };
            };
        };
    };
    workspace_import_api_v1_workspace_import_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WorkspaceImportRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkspaceImportResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
