/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/countries": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Countries */
        get: operations["countries_api_v1_countries_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/data/validate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Data Validate */
        post: operations["data_validate_api_v1_data_validate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_v1_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/macro/chart-data": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Macro Chart Data */
        post: operations["macro_chart_data_api_v1_macro_chart_data_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/macro/cred-output": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Macro Cred Output */
        get: operations["macro_cred_output_api_v1_macro_cred_output_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/measures/{country}/{hazard}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Measures */
        get: operations["measures_api_v1_measures__country___hazard__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/scenario/run": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Scenario Run */
        post: operations["scenario_run_api_v1_scenario_run_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/scenario/{job_id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Scenario Cancel */
        post: operations["scenario_cancel_api_v1_scenario__job_id__cancel_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/scenario/{job_id}/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Scenario Stream */
        get: operations["scenario_stream_api_v1_scenario__job_id__stream_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/scenarios": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Scenarios */
        get: operations["list_scenarios_api_v1_scenarios_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/scenarios/{scenario_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Scenario */
        get: operations["get_scenario_api_v1_scenarios__scenario_id__get"];
        put?: never;
        post?: never;
        /** Delete Scenario */
        delete: operations["delete_scenario_api_v1_scenarios__scenario_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/scenarios/{scenario_id}/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Export Scenario */
        post: operations["export_scenario_api_v1_scenarios__scenario_id__export_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/scenarios/{scenario_id}/save": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Save Scenario */
        post: operations["save_scenario_api_v1_scenarios__scenario_id__save_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/temp/clear": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Temp Clear */
        post: operations["temp_clear_api_v1_temp_clear_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ChartDataDataset */
        ChartDataDataset: {
            /** Data */
            data?: (number | null)[];
            /** Label */
            label?: string | null;
        } & {
            [key: string]: unknown;
        };
        /** ChartDataPayload */
        ChartDataPayload: {
            /** Datasets */
            datasets?: components["schemas"]["ChartDataDataset"][];
            /**
             * Title
             * @default
             */
            title: string;
            /** Years */
            years?: (number | string)[];
        } & {
            [key: string]: unknown;
        };
        /** CountriesResponse */
        CountriesResponse: {
            /** Data */
            data: components["schemas"]["Country"][];
            status: components["schemas"]["Status"];
        };
        /** Country */
        Country: {
            /** Code */
            code: string;
            /** Name */
            name: string;
        };
        /** DataValidateData */
        DataValidateData: {
            /** Data */
            data: {
                [key: string]: unknown;
            };
        };
        /** DataValidateRequest */
        DataValidateRequest: {
            /** Country */
            country: string;
            /** Datatype */
            dataType: string;
        };
        /** DataValidateResponse */
        DataValidateResponse: {
            data: components["schemas"]["DataValidateData"];
            status: components["schemas"]["Status"];
        };
        /** DeleteReportResponse */
        DeleteReportResponse: {
            /** Data */
            data: {
                [key: string]: unknown;
            };
            status: components["schemas"]["Status"];
        };
        /** ExportReportData */
        ExportReportData: {
            /**
             * Report Path
             * @default
             */
            report_path: string;
        };
        /**
         * ExportReportRequest
         * @description Body posted to ``POST /api/v1/scenarios/{id}/export``.
         *
         *     ``scenarioRunCode`` is overwritten by the FastAPI handler with the path
         *     parameter, so the field is optional in the body.
         */
        ExportReportRequest: {
            /** Exporttype */
            exportType: string;
            /** Report */
            report?: {
                [key: string]: unknown;
            } | null;
            /** Scenarioruncode */
            scenarioRunCode?: string | null;
        } & {
            [key: string]: unknown;
        };
        /** ExportReportResponse */
        ExportReportResponse: {
            data: components["schemas"]["ExportReportData"];
            status: components["schemas"]["Status"];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            /**
             * Status
             * @constant
             */
            status: "ok";
        };
        /** JobAcceptedResponse */
        JobAcceptedResponse: {
            /**
             * Job Id
             * @description UUID for the long-running scenario job
             */
            job_id: string;
        };
        /** MacroChartDataRequest */
        MacroChartDataRequest: {
            /** Countryname */
            countryName?: string | null;
            /** Scenario */
            scenario?: string | null;
            /** Sector */
            sector?: string | null;
            /** Variable */
            variable?: string | null;
        } & {
            [key: string]: unknown;
        };
        /** MacroChartDataResponse */
        MacroChartDataResponse: {
            data: components["schemas"]["ChartDataPayload"];
            status: components["schemas"]["Status"];
        };
        /**
         * MacroCredOutputResponse
         * @description The CRED output is a flat list of dict rows whose keys vary by export.
         *
         *     Frontend code groups and filters them client-side, so we don't pin a row
         *     schema here.
         */
        MacroCredOutputResponse: {
            /** Data */
            data: {
                [key: string]: unknown;
            }[];
            status: components["schemas"]["Status"];
        };
        /** MeasuresData */
        MeasuresData: {
            /** Adaptationmeasures */
            adaptationMeasures: string[];
        };
        /** MeasuresResponse */
        MeasuresResponse: {
            data: components["schemas"]["MeasuresData"];
            status: components["schemas"]["Status"];
        };
        /**
         * ReportItem
         * @description One persisted report row.
         *
         *     The legacy storage layer attaches arbitrary metadata to each report; we
         *     accept any extra keys and only validate the ones the UI actively reads.
         */
        ReportItem: {
            /** Data */
            data?: {
                [key: string]: unknown;
            } | null;
            /** Id */
            id: string;
            /** Image */
            image?: string | null;
            /** Scenario Id */
            scenario_id?: string | null;
            /** Type */
            type?: string | null;
        } & {
            [key: string]: unknown;
        };
        /** ReportListResponse */
        ReportListResponse: {
            /** Data */
            data: components["schemas"]["ReportItem"][];
            status: components["schemas"]["Status"];
        };
        /** ReportResponse */
        ReportResponse: {
            data: components["schemas"]["ReportItem"];
            status: components["schemas"]["Status"];
        };
        /** SaveScenarioResponse */
        SaveScenarioResponse: {
            data: components["schemas"]["SaveScenarioResponseData"];
            status: components["schemas"]["Status"];
        };
        /** SaveScenarioResponseData */
        SaveScenarioResponseData: {
            /** Data */
            data: {
                [key: string]: unknown;
            };
        };
        /**
         * ScenarioRunRequest
         * @description Inputs the renderer collects before kicking off a scenario run.
         *
         *     The CLIMADA layer reads these as plain strings/ints; we keep the model
         *     permissive so users can submit only the subset of fields a given hazard or
         *     exposure flow actually needs.
         */
        ScenarioRunRequest: {
            /** Annualgrowth */
            annualGrowth?: number | null;
            /** Countryname */
            countryName?: string | null;
            /** Exposureeconomic */
            exposureEconomic?: string | null;
            /** Exposurefile */
            exposureFile?: string | null;
            /** Exposurenoneconomic */
            exposureNonEconomic?: string | null;
            /** Hazardfile */
            hazardFile?: string | null;
            /** Hazardtype */
            hazardType?: string | null;
            /** Isera */
            isEra?: boolean | null;
            /** Scenario */
            scenario?: string | null;
            /** Timehorizon */
            timeHorizon?: number[] | null;
        } & {
            [key: string]: unknown;
        };
        /** Status */
        Status: {
            /** Code */
            code: number;
            /**
             * Message
             * @default
             */
            message: string;
        };
        /** TempClearResponse */
        TempClearResponse: {
            /** Error */
            error?: string | null;
            /** Message */
            message?: string | null;
            /** Success */
            success: boolean;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    countries_api_v1_countries_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CountriesResponse"];
                };
            };
        };
    };
    data_validate_api_v1_data_validate_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DataValidateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DataValidateResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_api_v1_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    macro_chart_data_api_v1_macro_chart_data_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MacroChartDataRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MacroChartDataResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    macro_cred_output_api_v1_macro_cred_output_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MacroCredOutputResponse"];
                };
            };
        };
    };
    measures_api_v1_measures__country___hazard__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                country: string;
                hazard: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeasuresResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    scenario_run_api_v1_scenario_run_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ScenarioRunRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobAcceptedResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    scenario_cancel_api_v1_scenario__job_id__cancel_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    scenario_stream_api_v1_scenario__job_id__stream_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_scenarios_api_v1_scenarios_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReportListResponse"];
                };
            };
        };
    };
    get_scenario_api_v1_scenarios__scenario_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                scenario_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReportResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_scenario_api_v1_scenarios__scenario_id__delete: {
        parameters: {
            query?: {
                report_type?: string;
                image?: string | null;
            };
            header?: never;
            path: {
                scenario_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeleteReportResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    export_scenario_api_v1_scenarios__scenario_id__export_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                scenario_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExportReportRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExportReportResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    save_scenario_api_v1_scenarios__scenario_id__save_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                scenario_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SaveScenarioResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    temp_clear_api_v1_temp_clear_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TempClearResponse"];
                };
            };
        };
    };
}
