"""Pydantic models for the RISK WISE FastAPI backend.

Exporting from a single place keeps the OpenAPI schema names stable and lets
``app.py`` import any model from ``models`` rather than walking the package.
"""

from backend.models.common import Status, StatusEnvelope
from backend.models.costbenefit import CostBenefitMeasure, CostBenefitPayload, CostBenefitResponse
from backend.models.countries import CountriesData, CountriesResponse, Country
from backend.models.custom_data import (
    CustomCountryEntry,
    CustomDataDeleteData,
    CustomDataDeleteResponse,
    CustomDataImportData,
    CustomDataImportRequest,
    CustomDataImportResponse,
    CustomDataListData,
    CustomDataListResponse,
    CustomDataValidateData,
    CustomDataValidateRequest,
    CustomDataValidateResponse,
)
from backend.models.data import DataValidateData, DataValidateRequest, DataValidateResponse

# Domain exception taxonomy lives in ``backend.models.errors`` and is
# imported directly there by callers — re-exporting names like
# ``ValidationError`` / ``CatalogError`` from this package would shadow
# Pydantic's and the engine's own classes of the same name.
from backend.models.errors import ErrorResponse
from backend.models.health import HealthResponse
from backend.models.macro import (
    ChartDataDataset,
    ChartDataPayload,
    CredDataset,
    CredDatasetDeleteData,
    CredDatasetDeleteResponse,
    CredDatasetsResponse,
    CredDatasetUploadRequest,
    CredDatasetUploadResponse,
    MacroChartDataRequest,
    MacroChartDataResponse,
    MacroCredOutputResponse,
)
from backend.models.measures import (
    Measure,
    MeasuresData,
    MeasureSet,
    MeasureSetDeleteData,
    MeasureSetDeleteResponse,
    MeasureSetsResponse,
    MeasureSetUploadRequest,
    MeasureSetUploadResponse,
    MeasuresResponse,
)
from backend.models.scenario import (
    JobAcceptedResponse,
    ScenarioErrorEvent,
    ScenarioProgressEvent,
    ScenarioResultEvent,
    ScenarioRunRequest,
)
from backend.models.scenarios import (
    CreateSnapshotRequest,
    CreateSnapshotResponse,
    DeleteScenarioResponse,
    DeleteSnapshotResponse,
    HydrateScenarioData,
    HydrateScenarioResponse,
    PatchScenarioRequest,
    SaveScenarioRequest,
    SaveScenarioResponse,
    ScenarioDetailPayload,
    ScenarioDetailResponse,
    ScenarioExportData,
    ScenarioExportResponse,
    ScenarioImportData,
    ScenarioImportRequest,
    ScenarioImportResponse,
    ScenarioListResponse,
    ScenarioWorkspaceItem,
    SnapshotItem,
    SnapshotListResponse,
    UpdateSnapshotRequest,
    UpdateSnapshotResponse,
)
from backend.models.settings import (
    ReportCurrency,
    ReportLocale,
    UpdateUserSettingsRequest,
    UserSettings,
    UserSettingsResponse,
)
from backend.models.temp import TempClearResponse
from backend.models.waterfall import WaterfallCategory, WaterfallPayload, WaterfallResponse
from backend.models.workspace import (
    WorkspaceExportData,
    WorkspaceExportResponse,
    WorkspaceImportData,
    WorkspaceImportRequest,
    WorkspaceImportResponse,
)

__all__ = [
    "ChartDataDataset",
    "ChartDataPayload",
    "CredDataset",
    "CredDatasetDeleteData",
    "CredDatasetDeleteResponse",
    "CredDatasetsResponse",
    "CredDatasetUploadRequest",
    "CredDatasetUploadResponse",
    "CostBenefitMeasure",
    "CostBenefitPayload",
    "CostBenefitResponse",
    "CreateSnapshotRequest",
    "CreateSnapshotResponse",
    "CountriesData",
    "CountriesResponse",
    "Country",
    "CustomCountryEntry",
    "CustomDataDeleteData",
    "CustomDataDeleteResponse",
    "CustomDataImportData",
    "CustomDataImportRequest",
    "CustomDataImportResponse",
    "CustomDataListData",
    "CustomDataListResponse",
    "CustomDataValidateData",
    "CustomDataValidateRequest",
    "CustomDataValidateResponse",
    "DataValidateData",
    "DataValidateRequest",
    "DataValidateResponse",
    "DeleteScenarioResponse",
    "DeleteSnapshotResponse",
    "ErrorResponse",
    "HealthResponse",
    "HydrateScenarioData",
    "HydrateScenarioResponse",
    "JobAcceptedResponse",
    "MacroChartDataRequest",
    "MacroChartDataResponse",
    "MacroCredOutputResponse",
    "Measure",
    "MeasureSet",
    "MeasureSetDeleteData",
    "MeasureSetDeleteResponse",
    "MeasureSetsResponse",
    "MeasureSetUploadRequest",
    "MeasureSetUploadResponse",
    "MeasuresData",
    "MeasuresResponse",
    "PatchScenarioRequest",
    "SaveScenarioRequest",
    "SaveScenarioResponse",
    "ScenarioDetailPayload",
    "ScenarioDetailResponse",
    "ScenarioExportData",
    "ScenarioExportResponse",
    "ScenarioImportData",
    "ScenarioImportRequest",
    "ScenarioImportResponse",
    "ScenarioListResponse",
    "ScenarioWorkspaceItem",
    "SnapshotItem",
    "SnapshotListResponse",
    "ScenarioErrorEvent",
    "ScenarioProgressEvent",
    "ScenarioResultEvent",
    "ScenarioRunRequest",
    "Status",
    "StatusEnvelope",
    "TempClearResponse",
    "ReportCurrency",
    "ReportLocale",
    "UpdateSnapshotRequest",
    "UpdateSnapshotResponse",
    "UpdateUserSettingsRequest",
    "UserSettings",
    "UserSettingsResponse",
    "WaterfallCategory",
    "WaterfallPayload",
    "WaterfallResponse",
    "WorkspaceExportData",
    "WorkspaceExportResponse",
    "WorkspaceImportData",
    "WorkspaceImportRequest",
    "WorkspaceImportResponse",
]
