"""Regenerate ``NOTICES.txt`` from a CycloneDX SBOM.

Run from the repo root::

    python scripts/generate_notices.py [--sbom path/to/sbom.json] [--output NOTICES.txt] [--check]

The script consumes a CycloneDX 1.5 JSON SBOM produced by ``cyclonedx-npm`` /
``cyclonedx-py`` (merged) and emits a static-data + dependency attribution
file. It is the single source of truth for ``NOTICES.txt``: the file is
checked into the repo for auditability, and CI fails if the regenerated
output diverges from the committed copy.

Determinism rules — running this script twice on the same SBOM must produce
bit-identical bytes:

  * Components are sorted by ``(group, name, version)`` with case-folded keys
    so platform-specific filesystem ordering does not leak in.
  * The generator never reads the wall clock — no timestamps in the output.
  * Static asset blocks (GADM, OSM, climate-lama-engine, Inter) are emitted
    in a fixed order from the constants below.
  * The file ends with a single trailing ``\n`` and uses LF line endings on
    every platform.
"""

from __future__ import annotations

import argparse
import json
import sys
from collections.abc import Iterable
from pathlib import Path
from typing import TypedDict

REPO_ROOT = Path(__file__).resolve().parent.parent
DEFAULT_SBOM = REPO_ROOT / "sbom.json"
DEFAULT_OUTPUT = REPO_ROOT / "NOTICES.txt"

HEADER = """RISK WISE v2 — third-party attribution

This file is generated by `scripts/generate_notices.py` from the project
SBOM (`sbom.json`). Do not edit by hand: CI regenerates the file on every
release and fails if the committed copy differs from the generated output.

The static-asset section lists data sources and fonts that ship as bundled
artifacts and are therefore not present in the SBOM. The dependency section
lists every npm and pip package the build resolves, with its license
identifier and homepage URL.
"""


class StaticAsset(TypedDict):
    title: str
    license: str
    homepage: str
    notice: str


# IMPORTANT: verify GADM non-commercial clause before commercial release.
STATIC_ASSETS: list[StaticAsset] = [
    {
        "title": "GADM administrative boundaries",
        "license": "CC BY 4.0",
        "homepage": "https://gadm.org/",
        "notice": (
            "Database of Global Administrative Areas (GADM), version 4.x.\n"
            "Licensed under Creative Commons Attribution 4.0 International "
            "(CC BY 4.0).\n"
            "# IMPORTANT: verify GADM non-commercial clause before commercial release"
        ),
    },
    {
        "title": "OpenStreetMap raster tiles",
        "license": "ODbL-1.0",
        "homepage": "https://www.openstreetmap.org/copyright",
        "notice": (
            "Map data © OpenStreetMap contributors, available under the "
            "Open Database License (ODbL).\n"
            "Tiles courtesy of the OpenStreetMap Foundation; usage subject to "
            "the OSMF tile-usage policy."
        ),
    },
    {
        "title": "climate-lama-engine reference datasets",
        "license": "MIT",
        "homepage": "https://github.com/CortoMaltese3/climate-lama-engine",
        "notice": (
            "Hazard, exposure, and impact-function reference datasets "
            "redistributed under the climate-lama-engine MIT license. The "
            "engine compute layer replaces the legacy CLIMADA dependency "
            "removed in #166; refer to the upstream LICENSE in the "
            "climate-lama-engine repository for the full text."
        ),
    },
    {
        "title": "Inter font family",
        "license": "SIL OFL 1.1",
        "homepage": "https://rsms.me/inter/",
        "notice": (
            "Copyright (c) Rasmus Andersson. Licensed under the SIL Open "
            "Font License 1.1 (OFL-1.1)."
        ),
    },
]


class Component(TypedDict):
    ecosystem: str
    name: str
    version: str
    license: str
    homepage: str


_NPM_PURL_PREFIX = "pkg:npm/"
_PYPI_PURL_PREFIX = "pkg:pypi/"


def _ecosystem_from_purl(purl: str) -> str:
    if purl.startswith(_NPM_PURL_PREFIX):
        return "npm"
    if purl.startswith(_PYPI_PURL_PREFIX):
        return "pypi"
    return "other"


def _extract_license(component: dict) -> str:
    """Pull the SPDX id (or expression) out of a CycloneDX component entry.

    CycloneDX 1.5 allows ``licenses`` to be a list of either ``{license: {id}}``
    (SPDX shortname), ``{license: {name}}`` (free-text), or ``{expression}``
    (SPDX expression). We collapse all three to a single string so the output
    is uniform across npm and pip outputs.
    """
    licenses = component.get("licenses") or []
    parts: list[str] = []
    for entry in licenses:
        if not isinstance(entry, dict):
            continue
        if "expression" in entry:
            parts.append(str(entry["expression"]))
            continue
        lic = entry.get("license")
        if not isinstance(lic, dict):
            continue
        if "id" in lic:
            parts.append(str(lic["id"]))
        elif "name" in lic:
            parts.append(str(lic["name"]))
    if not parts:
        return "UNKNOWN"
    seen: set[str] = set()
    deduped: list[str] = []
    for part in parts:
        if part not in seen:
            seen.add(part)
            deduped.append(part)
    return " AND ".join(deduped)


def _extract_homepage(component: dict) -> str:
    """Pick the most useful URL from CycloneDX ``externalReferences``.

    Preference order: ``website`` > ``vcs`` > ``distribution`` > ``other``.
    Falls back to the empty string if nothing is recorded — the SBOM tool
    sometimes omits URLs for transitive deps.
    """
    refs = component.get("externalReferences") or []
    by_type: dict[str, str] = {}
    for ref in refs:
        if not isinstance(ref, dict):
            continue
        ref_type = str(ref.get("type", "")).lower()
        url = str(ref.get("url", ""))
        if ref_type and url and ref_type not in by_type:
            by_type[ref_type] = url
    for preferred in ("website", "vcs", "distribution", "issue-tracker", "other"):
        if preferred in by_type:
            return by_type[preferred]
    return ""


def _normalize_components(sbom: dict) -> list[Component]:
    raw = sbom.get("components") or []
    out: list[Component] = []
    for c in raw:
        if not isinstance(c, dict):
            continue
        purl = str(c.get("purl", ""))
        ecosystem = _ecosystem_from_purl(purl)
        if ecosystem == "other":
            continue
        name = str(c.get("name", "")).strip()
        version = str(c.get("version", "")).strip()
        if not name:
            continue
        out.append(
            {
                "ecosystem": ecosystem,
                "name": name,
                "version": version,
                "license": _extract_license(c),
                "homepage": _extract_homepage(c),
            }
        )
    seen: set[tuple[str, str, str]] = set()
    deduped: list[Component] = []
    for comp in sorted(
        out,
        key=lambda c: (
            c["ecosystem"],
            c["name"].casefold(),
            c["version"],
        ),
    ):
        key = (comp["ecosystem"], comp["name"].casefold(), comp["version"])
        if key in seen:
            continue
        seen.add(key)
        deduped.append(comp)
    return deduped


def _render_static_block() -> list[str]:
    lines = ["## Bundled data and fonts", ""]
    for asset in STATIC_ASSETS:
        lines.append(f"### {asset['title']}")
        lines.append(f"License: {asset['license']}")
        lines.append(f"Homepage: {asset['homepage']}")
        lines.append("")
        lines.extend(asset["notice"].splitlines())
        lines.append("")
    return lines


def _render_dependency_block(label: str, components: Iterable[Component]) -> list[str]:
    items = list(components)
    lines = [f"## {label} dependencies ({len(items)})", ""]
    if not items:
        lines.append("(none)")
        lines.append("")
        return lines
    for comp in items:
        version = comp["version"] or "(unspecified)"
        homepage = comp["homepage"] or "(no homepage recorded)"
        lines.append(f"- {comp['name']}@{version}")
        lines.append(f"    license: {comp['license']}")
        lines.append(f"    homepage: {homepage}")
    lines.append("")
    return lines


def render_notices(sbom: dict) -> str:
    components = _normalize_components(sbom)
    npm = [c for c in components if c["ecosystem"] == "npm"]
    pypi = [c for c in components if c["ecosystem"] == "pypi"]
    parts: list[str] = []
    parts.extend(HEADER.rstrip("\n").splitlines())
    parts.append("")
    parts.extend(_render_static_block())
    parts.extend(_render_dependency_block("npm", npm))
    parts.extend(_render_dependency_block("pip", pypi))
    return "\n".join(parts).rstrip("\n") + "\n"


def _load_sbom(path: Path) -> dict:
    with path.open("r", encoding="utf-8") as fh:
        return json.load(fh)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--sbom",
        type=Path,
        default=DEFAULT_SBOM,
        help="Path to the merged CycloneDX SBOM (default: ./sbom.json).",
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=DEFAULT_OUTPUT,
        help="Path to write NOTICES.txt to (default: ./NOTICES.txt).",
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help=(
            "Do not overwrite the output file. Instead, regenerate the "
            "content in memory and exit non-zero if it differs from the "
            "committed copy. CI uses this mode."
        ),
    )
    args = parser.parse_args(argv)

    if not args.sbom.exists():
        print(f"error: SBOM not found: {args.sbom}", file=sys.stderr)
        return 2

    sbom = _load_sbom(args.sbom)
    rendered = render_notices(sbom)

    if args.check:
        if not args.output.exists():
            print(
                f"error: --check requested but {args.output} does not exist",
                file=sys.stderr,
            )
            return 1
        existing = args.output.read_text(encoding="utf-8")
        if existing != rendered:
            print(
                f"error: {args.output} is out of date. "
                "Run `python scripts/generate_notices.py` to regenerate.",
                file=sys.stderr,
            )
            return 1
        return 0

    args.output.write_text(rendered, encoding="utf-8", newline="\n")
    print(f"Wrote {args.output} ({len(rendered)} bytes)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
